# Generated by Django 4.2.7 on 2023-11-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('pkboard', models.AutoField(primary_key=True, serialize=False)),
                ('strBoardTitle', models.CharField(max_length=100)),
                ('strName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'job_board',
            },
        ),
    ]
