# Generated by Django 4.2.7 on 2023-11-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boardlist',
            table='wwwdb.dbo.job_board',
        ),
    ]
