# Generated by Django 4.2.7 on 2023-11-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_boardlist_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardlist',
            old_name='pkboard',
            new_name='pk_board',
        ),
        migrations.AlterModelTable(
            name='boardlist',
            table='job_board',
        ),
    ]
